/**
 * Type definitions for the application
 */

// User roles
export type UserRole = 'ADMIN' | 'PROJECT_MANAGER' | 'DEVELOPER';

// User interface
export interface User {
  id: string;
  email: string;
  displayName: string;
  photoURL?: string;
  role: UserRole;
  createdAt: Date;
  updatedAt: Date;
  isActive: boolean;
}

// Project interface
export interface Project {
  id?: string;
  name: string;
  description: string;
  icon?: string;
  color?: string;
  ownerId: string;
  teamMembers?: string[];
  members?: ProjectMember[];
  status: ProjectStatus;
  createdAt: Date | any;
  updatedAt: Date | any;
  taskCount?: number;
  completedCount?: number;
  isArchived?: boolean;
}

export type ProjectStatus = 'ACTIVE' | 'PAUSED' | 'ON_HOLD' | 'ARCHIVED';

// Project member interface
export interface ProjectMember {
  userId: string;
  email: string;
  displayName: string;
  role: 'OWNER' | 'MANAGER' | 'MEMBER';
  joinedAt: Date;
}

// Task priority levels
export type TaskPriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';

// Task status
export type TaskStatus = 'TODO' | 'IN_PROGRESS' | 'DONE';

// Task/Issue interface
export interface Task {
  id: string;
  projectId: string;
  title: string;
  description: string;
  assigneeId?: string;
  assignee?: User;
  status: TaskStatus;
  priority: TaskPriority;
  aiSummary?: string; // Generated by OpenAI API
  estimatedHours?: number;
  createdById: string;
  createdAt: Date;
  updatedAt: Date;
  updatedById: string;
  dueDate?: Date;
  labels?: string[];
}

// Analytics data
export interface TaskMetrics {
  total: number;
  completed: number;
  inProgress: number;
  todo: number;
  completionRate: number;
}

export interface UserWorkload {
  userId: string;
  displayName: string;
  taskCount: number;
  completedCount: number;
  assignedTasks: Task[];
}

export interface ProjectAnalytics {
  projectId: string;
  projectName: string;
  totalTasks: TaskMetrics;
  userWorkloads: UserWorkload[];
  tasksByPriority: Record<TaskPriority, number>;
  tasksByStatus: Record<TaskStatus, number>;
  completionTrend: Array<{
    date: string;
    completed: number;
  }>;
}

// AI Request/Response interfaces
export interface AIAnalysisRequest {
  title: string;
  description: string;
}

export interface AIAnalysisResponse {
  summary: string;
  suggestedPriority: TaskPriority;
  estimatedHours?: number;
}

// Issue priority levels
export type IssuePriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';

// Issue status
export type IssueStatus = 'OPEN' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED';

// Issue type
export type IssueType = 'BUG' | 'FEATURE' | 'ENHANCEMENT' | 'DOCUMENTATION';

// Issue comment interface
export interface IssueComment {
  authorId: string;
  content: string;
  createdAt: Date | any;
}

// Issue interface
export interface Issue {
  id?: string;
  projectId: string;
  title: string;
  description: string;
  status: IssueStatus;
  priority: IssuePriority;
  type: IssueType;
  assigneeId: string | null;
  reportedById: string;
  createdAt: Date | any;
  updatedAt: Date | any;
  comments?: IssueComment[];
  attachments?: string[];
}

// API Response wrapper
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}
